version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD={{ mysql_root_password }}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 25765:3306

    
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 25764:8080

volumes:
  mysql_data:
