version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=Asia/Taipei
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 25765:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 25764:8080
  
  server:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - 25763:8080
      - 25664:5000
    environment:
      - TZ=Asia/Taipei
    #   - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ${TIMECONFIG}:/app/Config/TimeConfig.json:ro
      - ${APPSETTINGS}:/app/appsettings.json:ro
      - ${APPLOGS}:/app/Logs
volumes:
  mysql_data:
